import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {migrateLocal,d1Adapter} from '../scripts/sqlite-adapter.mjs';
import worker from '../dist/server/index.js';
import {dateKey} from '../public/model.js';
function database(){const sql=new DatabaseSync(':memory:');migrateLocal(sql);return d1Adapter(sql);}
function req(path='/api/state',user='alice',body,origin='https://ember.test'){const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'};if(body!==undefined){headers.origin=origin;headers['content-type']='application/json';}if(!user)delete headers['oai-authenticated-user-id'];return new Request('https://ember.test'+path,{headers,method:body===undefined?'GET':'POST',...(body===undefined?{}:{body:JSON.stringify(body)})});}
const version={name:'Focus',icon:'book',color:'green',days:[0,1,2,3,4,5,6],tasks:[{id:'a',title:'Read'},{id:'b',title:'Write'}]};
const create={type:'save-routine',id:'focus',version};
test('API rejects anonymous reads and writes',async()=>{const env={DB:database()};assert.equal((await worker.fetch(req('/api/state',''),env)).status,401);assert.equal((await worker.fetch(req('/api/actions','',create),env)).status,401);});
test('Cross-origin writes are rejected',async()=>{assert.equal((await worker.fetch(req('/api/actions','alice',create,'https://bad.test'),{DB:database()})).status,403);});
test('Database retains changes across independent requests and isolates users',async()=>{const env={DB:database()};assert.equal((await worker.fetch(req('/api/actions','alice',create),env)).status,200);const a=await(await worker.fetch(req('/api/state','alice'),env)).json();const b=await(await worker.fetch(req('/api/state','bob'),env)).json();assert.equal(a.data.routines.length,1);assert.equal(b.data.routines.length,0);assert.equal(a.revision,1);});
test('Two simultaneous devices do not lose separate task completions',async()=>{const env={DB:database()};await worker.fetch(req('/api/actions','alice',create),env);const day=dateKey(new Date(),'Europe/Bratislava');const responses=await Promise.all(['a','b'].map(taskId=>worker.fetch(req('/api/actions','alice',{type:'check',day,routineId:'focus',taskId,done:true}),env)));assert.ok(responses.every(r=>r.status===200));const result=await(await worker.fetch(req('/api/state','alice'),env)).json();assert.equal(Object.keys(result.data.checks[day]).length,2);assert.equal(result.revision,3);});
test('Validation failure does not alter saved account data',async()=>{const env={DB:database()};await worker.fetch(req('/api/actions','alice',create),env);assert.equal((await worker.fetch(req('/api/actions','alice',{type:'import',data:{}}),env)).status,400);const result=await(await worker.fetch(req('/api/state','alice'),env)).json();assert.equal(result.revision,1);assert.equal(result.data.routines.length,1);});
test('Unavailable storage returns a recoverable error',async()=>{assert.equal((await worker.fetch(req(),{})).status,503);});
test('All app entry points and install assets are served with correct types',async()=>{for(const [path,type]of [['/','text/html'],['/app.js','text/javascript'],['/styles.css','text/css'],['/manifest.webmanifest','application/manifest+json'],['/icon-192.png','image/png'],['/icon-512.png','image/png'],['/sw.js','text/javascript'],['/offline.html','text/html']]){const r=await worker.fetch(req(path),{});assert.equal(r.status,200,path);assert.ok(r.headers.get('content-type').startsWith(type),path);assert.ok((await r.arrayBuffer()).byteLength>0,path);}});
test('Auth and user data are never cached by service worker',async()=>{const r=await worker.fetch(req('/sw.js'),{});const text=await r.text();assert.ok(text.includes("url.pathname.startsWith('/api/')"));assert.ok(text.includes("url.pathname.includes('chatgpt')"));assert.ok(!text.includes('cache.put'));const api=await worker.fetch(req(),{DB:database()});assert.equal(api.headers.get('cache-control'),'no-store');});
